name: Package

on:
  push:
    tags:
      - "[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:

  bdist_wheel:

    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Build wheels
        uses: pypa/cibuildwheel@v1.11.1.post1
        with:
          output-dir: dist
        env:
            WRAPT_INSTALL_EXTENSIONS: true  # fail if extensions doesn't compile
            CIBW_SKIP: pp*                  # skip building wheels for PyPy
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.whl

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build source distribution
      run: python setup.py sdist
    - name: Store built wheels
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*

  upload:
    environment: PyPI
    runs-on: ubuntu-latest
    name: Upload
    needs:
    - sdist
    - bdist_wheel
    steps:
    - name: Download built distributions
      uses: actions/download-artifact@v4.1.7
      with:
          name: dist
          path: dist
    - name: Publish distributions to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: false
